/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.mup;

import java.awt.event.ActionListener;
import javax.swing.JCheckBox;

/**
 *
 * @author Sumit_Saseendran
 */
public class Installer extends javax.swing.JPanel {

    /**
     * Creates new form panel3sub3
     */
    public Installer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox32bit = new javax.swing.JCheckBox();
        jCheckBox64bit = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(527, 673));

        jCheckBox32bit.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jCheckBox32bit.setSelected(true);
        jCheckBox32bit.setText("32-bit Installer");
        jCheckBox32bit.setEnabled(false);
        jCheckBox32bit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox32bitActionPerformed(evt);
            }
        });

        jCheckBox64bit.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jCheckBox64bit.setSelected(true);
        jCheckBox64bit.setText("64-bit Installer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox64bit)
                    .addComponent(jCheckBox32bit))
                .addContainerGap(351, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jCheckBox32bit)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox64bit)
                .addContainerGap(544, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox32bitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox32bitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox32bitActionPerformed

    public void setButtonsActionListener(ActionListener listener){
        jCheckBox32bit.addActionListener(listener);
        jCheckBox64bit.addActionListener(listener);
    }

    public JCheckBox getjCheckBox1() {
        return jCheckBox32bit;
    }

    public JCheckBox getjCheckBox2() {
        return jCheckBox64bit;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox32bit;
    private javax.swing.JCheckBox jCheckBox64bit;
    // End of variables declaration//GEN-END:variables

    public void clearField() {
        jCheckBox32bit.setSelected(true);
        jCheckBox64bit.setSelected(true);
    }
}
